/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:f95c6db3-80d9-444f-a3fa-23237c22a8b2",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_SitDZSzx6",
    "aws_user_pools_web_client_id": "kripq400b2aa1k9sfpo9emds9",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://cj4pakenzrgbhlewrzld3s4bqu.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_dynamodb_all_tables_region": "us-east-1",
    "aws_dynamodb_table_schemas": [
        {
            "tableName": "dish-dev",
            "region": "us-east-1"
        }
    ]
};


export default awsmobile;
