/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:f95c6db3-80d9-444f-a3fa-23237c22a8b2",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_SitDZSzx6",
    "aws_user_pools_web_client_id": "kripq400b2aa1k9sfpo9emds9",
    "oauth": {}
};


export default awsmobile;
